#!/bin/sh

set -e

#./.init.sh all
scriptpath= SCRIPTPATH= bats test/baseline/mainlibs.bats
./.init.sh check

#scriptpath= SCRIPTPATH= bats test/baseline/{bash,realpath,git,bats,redo}*.bats
#scriptpath= SCRIPTPATH= bats test/unit/{os,lib,logger}*bats
#scriptpath= SCRIPTPATH= bats test/unit/{sys,shell,str,date}*bats
#scriptpath= SCRIPTPATH= bats test/unit/*bats
#scriptpath= SCRIPTPATH= bats test/spec/*bats

#./bin/u-s dckr-init
