jobs:
  build:

    # The start dir is ~/project, there is a helper to create the checkout
    docker:
      - image: dotmpe/treebox:edge

    steps:

    # Invoke CCI helper.
    - checkout

    # Go move checkout to a default build location ~/project/user-scripts
    - run:
        name: Setup
        command: |
          # XXX: not sure if these commands are executing in login-shell
          . ~/.profile
          # Prepare .test-env.sh file and overwrite ~/.profile
          . ./tools/ci/setup.sh
          { echo "# Added by $0:Setup on $(date --iso=min)"
            echo export scriptname=Circle-CI
          } >> ~/.profile
          # Log-profile needs a bit of special attention, check here
          #set -x
          . ./.test-env.sh

    #- run:
    #    name: Move checkout
    #    command: |
    #        echo "$(whoami)@$(hostname -f):$PWD"; cd; \
    #        mv ~/project/ ~/user-scripts; \
    #        mkdir ~/project; \
    #        mv ~/user-scripts/ ~/project/; \
    #        ln -s ~/project/user-scripts ~/bin; \
    #        cd ~/project/user-scripts

    - run:
        name: Build
        command: |
          . ./.test-env.sh
          . ./sh-ci

    - store_artifacts:
        path: reports/

    - store_test_results:
        path: reports/

# Id: U-S:circleci/config.yml
