jobs:
  build:

    # The start dir is ~/project, there is a helper to create the checkout
    docker:
      - image: dotmpe/treebox:edge

    steps:

    # Invoke CCI helper.
    - checkout

    # Go move checkout to a default build location ~/project/user-scripts
    - run:
        name: Setup
        command: |
          . ~/.profile
          . ./tools/ci/setup.sh
          echo export scriptname=Circle-CI >> ~/.profile

    #- run:
    #    name: Move checkout
    #    command: |
    #        echo "$(whoami)@$(hostname -f):$PWD"; cd; \
    #        mv ~/project/ ~/user-scripts; \
    #        mkdir ~/project; \
    #        mv ~/user-scripts/ ~/project/; \
    #        ln -s ~/project/user-scripts ~/bin; \
    #        cd ~/project/user-scripts

    - run:
        name: Build
        command: |
          . ./test-env.sh
          . ./sh-ci

    - store_artifacts:
        path: reports/

    - store_test_results:
        path: reports/

# Id: U-S:circleci/config.yml
