#!/usr/bin/env bash
#
# us-build, us-run - us-pp wrapper for building and executing user script files
# 
# Copyright 2018-2026 B. van Berkum <dev@dotmpe.com>
#
# Distributed under terms of the MIT license.

#
# Copyright 2008-2026 B. van Berkum <dev@dotmpe.com>
#
# Distributed under terms of the MIT license.
: "${DEBUG:=0}"
: "${QUIET:=0}"
! ((DEBUG)) || {
  shopt -s extdebug
  PS4='\[\033[0m\]${BASH_SOURCE:+\[\033[34m\]$BASH_SOURCE\[\033[36m\]:\[\033[32m\]${LINENO}} \[\033[33m\]+\[\033[0m\] '
  ((QUIET)) ||
    >&2 echo "$$$-\$ $0 ${*@Q}"
}
# Id: debug.sh.h                                vim:set ft=bash sw=2 sts=2 et:
#
# Copyright 2008-2026 B. van Berkum <dev@dotmpe.com>
#
# Distributed under terms of the MIT license.
set -euo pipefail
IFS=$' \t\n'
# Id: strict.sh.h                               vim:set ft=bash sw=2 sts=2 et:
export LOG=$HOME/bin/tool/sh/log.sh
failerr () 
{ 
    userscripts::core::echo_stderr_with_status "$@"
}
userscripts::core::echo_stderr_with_status () 
{ 
    local stat=${2:-$?};
    : input "${1:?$FUNCNAME: Failure message, $ENV_CTX}";
    ((stat)) || stat=1;
    echo "$1" 1>&2;
    return ${stat};
    : alias failerr
}

_us_build_init ()
{
  # XXX: build us-pp too...
  . us-pp &&
  _us_pp_init &&
  _us_pp_load ||
    failerr "E$? Loading script env" || exit
}

: "${BASH_SOURCE[0]##*/}"
if [[ ${0##*/} == "${_%%.*}" || "${0##*/}" == "${_%%.*}".* ]]
then
  script_srcname="${BASH_SOURCE[0]##*/}"
  script_cmdname="${0##*/}"
  script_nameexts="${script_cmdname#*.}"
  # TODO: want may be to recognize current (script) language tag
  script_name="${script_cmdname%.*}"
  #[[ $script_name == *.* ]] &&
  script_basename="${script_srcname%%.*}"
  #shellcheck disable=1009,1054,1056,1072,1073,1083
  _us_build_init && "${script_name//[^A-Za-z0-9_]/_}_main" "$@"
fi
# vim:set ft=bash sw=2 sts=2 et:
