#!/usr/bin/env bash

if [[ ${US_BUILD_BASH_DEBUG:+set} ]]; then
  DEBUG=1
  set -x
fi

#
# Copyright 2008-2026 B. van Berkum <dev@dotmpe.com>
#
# Distributed under terms of the MIT license.
: "${DEBUG:=0}"
: "${QUIET:=0}"
! ((DEBUG)) || {
  shopt -s extdebug
  PS4='\[\033[0m\]${BASH_SOURCE:+\[\033[34m\]$BASH_SOURCE\[\033[36m\]:\[\033[32m\]${LINENO}} \[\033[33m\]+\[\033[0m\] '
  ((QUIET)) ||
    >&2 echo "$$$-\$ $0 ${*@Q}"
}
# Id: user-script.debug.sh.h                     vim:set ft=bash sw=2 sts=2 et:
#
# Copyright 2008-2026 B. van Berkum <dev@dotmpe.com>
#
# Distributed under terms of the MIT license.
set -euo pipefail
IFS=$' \t\n'
# Id: strict.sh.h                                vim:set ft=bash sw=2 sts=2 et:
if [ -z "${LOG-}" ]
then
  if [ -x ~/bin/tool/sh/log.sh ]
  then LOG=$HOME/bin/tool/sh/log.sh
  fi
fi
if_ok "$(declare -F "failerr")" ||
failerr () 
{ 
    userscripts::core::echo_stderr_with_status "$@"
}
if_ok "$(declare -F "userscripts::core::echo_stderr_with_status")" ||
userscripts::core::echo_stderr_with_status () 
{ 
    local stat=${2:-$?};
    : input "${1:?$FUNCNAME: Failure message, $ENV_CTX}";
    ((stat)) || stat=1;
    echo "$1" 1>&2;
    return ${stat};
    : alias failerr
}

_us_build_init ()
{
  # FIXME: this is dev setup, build us-pp too...
  . us-pp && _us_pp_init || failerr "E$? Loading script env" || exit
  # Integrate env 
  # loading additional scripts for preprocessor definitions
  if [[ ${ENV:+set} && ( ${ENV_PARTS:+pend} || ${ENV_PEND:+set} ) ]]
  then
    : # us_std_env || failerr "E$? setting up build env" || return
  else
    if [[ ${EWD:+set} ]]
    then
      export ENV=local ENV_PEND=local
      _us_pp_notice "Set local build env"
    else
      _us_pp_debug "No recognized build environment, continue with default us-pp"
    fi
  fi
}

_us_build_load ()
{
  _us_pp_debug "> $FUNCNAME: ${*@Q}"
  _us_pp_load "$@" || return
  local _arg
  for _arg
  do case "$_arg" in
  ( *.h )
      _us_pp_notice "PP off $_arg"
      us_pp_off=1
      us_gpp_mode=c_compat
    ;; esac
  done
}

: "${BASH_SOURCE[0]##*/}"
if [[ ${0##*/} == "${_%%.*}" || "${0##*/}" == "${_%%.*}".* ]]
then
  script_srcname="${BASH_SOURCE[0]##*/}"
  script_cmdname="${0##*/}"
  script_nameexts="${script_cmdname#*.}"
  # TODO: want may be to recognize current (script) language tag
  script_name="${script_cmdname%.*}"
  #[[ $script_name == *.* ]] &&
  script_basename="${script_srcname%%.*}"
  #shellcheck disable=1009,1054,1056,1072,1073,1083
  _us_build_init && _us_build_load "$@" && "${script_name//[^A-Za-z0-9_]/_}_main" "$@"
fi
# vim:set ft=bash sw=2 sts=2 et:
