#!/usr/bin/env bash

#
# Copyright 2008-2026 B. van Berkum <dev@dotmpe.com>
#
# Distributed under terms of the MIT license.
: "${DEBUG:=0}"
: "${QUIET:=0}"
! ((DEBUG)) || {
  shopt -s extdebug
  PS4='\[\033[0m\]${BASH_SOURCE:+\[\033[34m\]$BASH_SOURCE\[\033[36m\]:\[\033[32m\]${LINENO}} \[\033[33m\]+\[\033[0m\] '
  ((QUIET)) ||
    >&2 echo "$$$-\$ $0 ${*@Q}"
}
# Id: user-script.debug.sh.h                     vim:set ft=bash sw=2 sts=2 et:
#
# Copyright 2008-2026 B. van Berkum <dev@dotmpe.com>
#
# Distributed under terms of the MIT license.
set -euo pipefail
IFS=$' \t\n'
# Id: strict.sh.h                                vim:set ft=bash sw=2 sts=2 et:
if [ -z "${LOG-}" ]
then
  if [ -x ~/bin/tool/sh/log.sh ]
  then LOG=$HOME/bin/tool/sh/log.sh
  fi
fi
if_ok "$(declare -F "failerr")" ||
failerr () 
{ 
    userscripts::core::echo_stderr_with_status "$@"
}
if_ok "$(declare -F "userscripts::core::echo_stderr_with_status")" ||
userscripts::core::echo_stderr_with_status () 
{ 
    local stat=${2:-$?};
    : input "${1:?$FUNCNAME: Failure message, $ENV_CTX}";
    ((stat)) || stat=1;
    echo "$1" 1>&2;
    return ${stat};
    : alias failerr
}

_us_pp_init ()
{
  if [[ ${U_S:+set} ]]
  then
    # Load parts and generate functions to map some namespaced names
    
    PATH+=:$U_S/tool/bash/part
    . us-core.inc.bash
    . us-pp-core.inc.bash
    . us-pp-cli.inc.bash
    . us-shell.inc.bash
    . us-str.inc.bash
    . us-use.inc.bash

    userscripts::use userscripts::core
    userscripts::use userscripts::string
    userscripts::use userscripts::preproc
    if [[ ${ENV:+set} ]]; then
      userscripts::use userscripts::stdenv
    fi
  else
    >&2 echo "$$ us-pp: cannot continue without User-Script env"
  fi
}

_us_pp_load ()
{
  _us_pp_debug "> $FUNCNAME: ${*@Q}"
  local _arg
  for _arg
  do case "$_arg" in
  ( --lang=* )
      us_pp_lang=${_arg:7}
    ;;
  ( --pwd )
      export EWD=$PWD
    ;; esac
  done

  # Make app user-data driven (load data into these from config)
  declare -gA us_pp_{snip,snip_literal} us_gpp_subs
  declare -ga us_pp_{config,inc}s us_gpp_defs

  : "${UC_DATA_DIR:=/var/local/statusdir}"
  assert_absolute "${us_pp_data:=$UC_DATA_DIR/pp,uc.data.bash}" \
    "Use absolute paths for configuration (us-pp-data = ${us_pp_data@Q})" || return

  #cache_loadmaps "$us_pp_data" us_pp_{snip,snip_literal,lang}
  [[ ! -s $us_pp_data ]] || . "$us_pp_data" ||
    failerr "E$? while loading us-pp-data ${us_pp_data@Q}" || return

  # NOTE: wont load relative paths unless caller sets up EWD to indicate
  # basedir, not going to assume implied PWD as basedir for current env.
  #local -n ref=us_pp_config
  local ref
  for ref in "${us_pp_configs[@]}"
  do
    [[ "${ref:0:1}" == / ]] || {
      [[ ${EWD:+set} ]] || {
        [[ ! -e "$ref" ]] ||
        >&2 echo "Set EWD for relative path config (ignored: ${ref@Q})"
        continue
      }
      ref=$EWD/$ref
    }

    [[ -e "$ref" ]] || continue
    us_pp_config=$ref
    . "$ref" ||
      failerr "E$? while loading ${ref@Q}" || return
  done

  # Default or additional defines (for GPP) are set per invocations. Default
  # includes (for both PP and GPP) we can add already here.
  [[ ${us_pp_incs[*]:+set} ]] || us_pp_incs+=( "$HOME/bin" "."  )

  [[ ! ${us_pp_lang:+set} ]] ||
  declare -gn us_pp_filter='uc_pp_prefilter["$us_pp_lang"]'
}

: "${BASH_SOURCE[0]##*/}"
if [[ ${0##*/} == "${_%%.*}" || "${0##*/}" == "${_%%.*}".* ]]
then
  script_srcname="${BASH_SOURCE[0]##*/}"
  script_cmdname="${0##*/}"
  script_nameexts="${script_cmdname#*.}"
  # TODO: want may be to recognize current (script) language tag
  script_name="${script_cmdname%.*}"
  #[[ $script_name == *.* ]] &&
  script_basename="${script_srcname%%.*}"
  #shellcheck disable=1009,1054,1056,1072,1073,1083
  _us_pp_init && _us_pp_load "$@" && us_pp_main "$@"; exit
fi

# vim:set ft=bash sw=2 sts=2 et:
